### ISSUE TITLE
How to get operation space dynamic?

### ISSUE THREAD

**Issue by skywoodsz** [Betancourt20/Pinocchio_examples#1]
Hi, I am also designing an impendance controller. But I do not know how to get operation space dynamics (e.g. cartesian inertia matrx, cartesian coriolis and centrifugal matrix) using Pinocchio. Could you please give me some tips? Thanks!

**Comment by Betancourt20** [comment]
Hi,
The  operation space dynamics is written by equations that are in functions of your joints. Thus, all of this equations are already given by Pinocchio such that you can build your space model "easily". Just remember that for instance, your Cartesian inertial matrix is equal to:
```math
\Lambda(q) = J^{-T}(q) M(q) J^{-1}(q)
```
Or you can do all the algebraic computation that brings you to the torque control which at the end is the same (see ImpedanceControl.ipynb).
 
Hope it helped ;)

**Comment by skywoodsz** [comment]
> Hi, The operation space dynamics is written by equations that are in functions of your joints. Thus, all of this equations are already given by Pinocchio such that you can build your space model "easily". Just remember that for instance, your Cartesian inertial matrix is equal to:
> 
> Λ(q)=J−T(q)M(q)J−1(q)
> Or you can do all the algebraic computation that brings you to the torque control which at the end is the same (see ImpedanceControl.ipynb).
> 
> Hope it helped ;)

Yeah, thanks a lot!
I learned your program and calculated torques in joint space, avoiding calculation of operation space dynamics. 
Thanks for your reply
